### ISSUE TITLE
Error mitm module.

### ISSUE THREAD

**Issue by Demigoddd** [4shadoww/usploit#2]
Add all options and pressed run.

https://prnt.sc/g5qf49
`sh: dsniff: not found`

Other sniffer (msgsnarf,urlsnarfdriftnet), Also tried, also an error.
How to fix?

**Comment by 4shadoww** [comment]
By running command "list dependencies" you will get list of dependencies that are required in order to use the module. So please install those and try again.

**Comment by Demigoddd** [comment]
@4shadoww Sorry did not notice.But it would be better if dnsiff added to framework.
